// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "cdcdx"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analytics/behaviors": {
            "get": {
                "description": "查询用户行为事件汇总数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分析"
                ],
                "summary": "行为摘要",
                "parameters": [
                    {
                        "type": "string",
                        "description": "事件类型(如order_create)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/analytics/daily": {
            "get": {
                "description": "查询PostgreSQL中的每日统计数据，支持日期范围筛选",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分析"
                ],
                "summary": "每日统计",
                "parameters": [
                    {
                        "type": "string",
                        "default": "__7DAYS_AGO__",
                        "description": "起始日期(YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "__TODAY__",
                        "description": "结束日期(YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/monitor/cache-stats": {
            "get": {
                "description": "返回L1本地缓存命中率和多级缓存统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "监控"
                ],
                "summary": "缓存统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/monitor/circuit-breaker": {
            "get": {
                "description": "查看当前熔断器状态(CLOSED/OPEN/HALF_OPEN)及详细指标",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "监控"
                ],
                "summary": "熔断器状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/monitor/metrics": {
            "get": {
                "description": "获取缓存命中率、QPS、熔断器状态等实时运行指标",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "监控"
                ],
                "summary": "服务指标",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/orders": {
            "post": {
                "description": "双通道分流：同步(限流内) | 异步(超限→Kafka)，适用于高并发写场景",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "创建订单 (异步)",
                "parameters": [
                    {
                        "description": "订单信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "channel": {
                                                    "type": "string"
                                                },
                                                "order_no": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/search": {
            "get": {
                "description": "通过Elasticsearch全文搜索订单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "搜索订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/sync": {
            "post": {
                "description": "强制同步写入MySQL，不走Kafka，立即可读",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "创建订单 (同步)",
                "parameters": [
                    {
                        "description": "订单信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "channel": {
                                                    "type": "string"
                                                },
                                                "order_no": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/{orderNo}": {
            "get": {
                "description": "通过订单号查询，走L1→L2→MySQL三级缓存",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单"
                ],
                "summary": "查询订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单号",
                        "name": "orderNo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.Order"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/profile": {
            "post": {
                "description": "MongoDB upsert 写入，同时更新缓存",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "创建/更新用户资料",
                "parameters": [
                    {
                        "description": "用户资料",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.UserProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.UserProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/search": {
            "get": {
                "description": "通过Elasticsearch全文搜索用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "搜索用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页条数",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{userID}/profile": {
            "get": {
                "description": "走多级缓存: L1→L2→L3(MongoDB)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询用户资料",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.UserProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cdcdx_high-concurrency-framework_internal_model.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        },
        "github_com_cdcdx_high-concurrency-framework_internal_model.Order": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_no": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "github_com_cdcdx_high-concurrency-framework_internal_model.UserProfile": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "高并发业务框架 API",
	Description:      "高并发业务处理框架，支持多级缓存、读写分离、异步消息、全文搜索等能力",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
